### ISSUE TITLE
where is lockscreen.sh

### ISSUE THREAD

**Issue by Yuzuru-Yamazaki** [Alopes01/Dotfiles#3]
bindsym $mod+c exec "~/.config/i3/lockscreen.sh" I can't find it

**Comment by Alopes01** [comment]
https://github.com/betterlockscreen/betterlockscreen you can use this, many use it. I didn't put it on purpose because i3 lock works fine if you change the color, I had that only to lock the screen and appear blurred. This one does the same thing. I hope it helped

**Comment by Yuzuru-Yamazaki** [comment]
ok
