### ISSUE TITLE
polybar again

### ISSUE THREAD

**Issue by Yuzuru-Yamazaki** [Alopes01/Dotfiles#5]
I saw the file and it really was commented but I need help with another error.The first one happened because I changed config.ini to config.but I went with the first on and it gave me this:
`polybar|error: Define configuration using --config=PATH`
plz help I'm a newbie

**Comment by Alopes01** [comment]
You just need to run polybar with `polybar --config /the/path/to/the/config` which is normally in the .config folder

**Comment by Alopes01** [comment]
So tell me did it work

**Comment by Yuzuru-Yamazaki** [comment]
I tried it and it worked at the moment , but i3 broke my mint install and had to timeshift to a saved snapshot :(

**Comment by Yuzuru-Yamazaki** [comment]
and if I remember correctly it was a little bigger for my screen , and I didn't know how to scale it down

**Comment by Alopes01** [comment]
Sorry to ear that bud

**Comment by Yuzuru-Yamazaki** [comment]
nah no problem
